#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

prepare_build() {
  if [ -d coverage ]; then
    rm -rf coverage
  fi
}

print_ruby_version() {
  echo "Using $(ruby -v)"
  echo
}

run_tests() {
  bundle exec rake test
}

main() {
  prepare_build &&
    print_ruby_version &&
    run_tests
}

main
